---
name: App-ZofCMS-Plugin-GetRemotePageTitle
version: 0.0104
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin to obtain page titles from remote URIs
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  WWW::GetPageTitle: 0.0102
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::GetRemotePageTitle:
    file: lib/App/ZofCMS/Plugin/GetRemotePageTitle.pm
    version: 0.0104
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
